#! /usr/bin/env ruby

# Copyright (C) 2012 Ness Computing, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

########################################################################
#
# Loads jvm.properties file from the config location
# and returns all the options for the JVM in a format that is suitable to be
# used for java $(jvm_opts) <program>
#
# Inspected files are
#
# <config-location>/jvm.properties  -- for local modifications / testing. Should be empty most of the time
# env/jvm.properties
# env/version/jvm.properties
# env/version/type/jvm.properties
#
# Elements in more specific locations override elements in more general locations.
#

require 'rubygems'
require 'galaxy/scripts'

scripts = Galaxy::ScriptSupport.new ARGV

puts scripts.get_jvm_opts.join(" ")

