#!/usr/bin/env ruby

# Copyright (C) 2012 Ness Computing, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

########################################################################
# The archive must contain at least one file, bin/xndeploy, that must
# return a 0 exit status. This script can do whatever is needed to
# deploy the application being installed. Note that most xndeploy
# scripts require the Galaxy library to be included in the archive,
# under lib/galaxy.

require 'rubygems'
require 'galaxy/scripts'

scripts = Galaxy::ScriptSupport.new ARGV

Dir.chdir scripts.base

unless system("bin/configure --slot-info #{scripts.slot_info}")
  raise "Unable to invoke the configure script!"
end
